update sequence and needs

diff --git a/.github/workflows/release_collection.yml b/.github/workflows/release_collection.yml
--- a/.github/workflows/release_collection.yml
+++ b/.github/workflows/release_collection.yml
@@ -22,23 +22,6 @@ on:
         required: false
 
 jobs:
-  release_galaxy:
-    runs-on: ubuntu-latest
-    environment: ${{ inputs.environment }}
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: "Build the collection"
-        run: |
-          ansible-galaxy collection build -v --force
-
-      - name: "Publish the collection on Galaxy"
-        if: ${{ inputs.galaxy_publish }}
-        run: |
-          [[ "${{ secrets.ansible_galaxy_api_key != '' }}" ]] || { echo "ansible_galaxy_api_key is required to publish on galaxy" ; exit 1; }
-          TARBALL=$(ls -1 ./*.tar.gz)
-          ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ansible_galaxy_api_key }}"
-
   release_automation_hub:
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
@@ -64,3 +47,21 @@ jobs:
           EOF
           ansible-galaxy collection publish "${TARBALL}"
           rm ansible.cfg
+
+  release_galaxy:
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    needs: [release_automation_hub]
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: "Build the collection"
+        run: |
+          ansible-galaxy collection build -v --force
+
+      - name: "Publish the collection on Galaxy"
+        if: ${{ inputs.galaxy_publish }}
+        run: |
+          [[ "${{ secrets.ansible_galaxy_api_key != '' }}" ]] || { echo "ansible_galaxy_api_key is required to publish on galaxy" ; exit 1; }
+          TARBALL=$(ls -1 ./*.tar.gz)
+          ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ansible_galaxy_api_key }}"
